// Generated by scripts/build-emoji-list.mjs from emoji-list.md — do not hand-edit, edit the md and rerun.
export const EMOJIS = [
  {
    "emoji": "😀",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😂",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "🤣",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😊",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😍",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "🥰",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😘",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😜",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "🤔",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😎",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😭",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😱",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😡",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "🥳",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😴",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "🤢",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "🤮",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😇",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "🙄",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😬",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "🥺",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "😏",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "🤯",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "🥵",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "🥶",
    "category": "Smileys & Emotion"
  },
  {
    "emoji": "👍🏽",
    "category": "Hand Gestures"
  },
  {
    "emoji": "👎🏽",
    "category": "Hand Gestures"
  },
  {
    "emoji": "👋🏾",
    "category": "Hand Gestures"
  },
  {
    "emoji": "✌️🏿",
    "category": "Hand Gestures"
  },
  {
    "emoji": "👌🏼",
    "category": "Hand Gestures"
  },
  {
    "emoji": "🤝",
    "category": "Hand Gestures"
  },
  {
    "emoji": "🙏🏽",
    "category": "Hand Gestures"
  },
  {
    "emoji": "👏🏼",
    "category": "Hand Gestures"
  },
  {
    "emoji": "🤞🏽",
    "category": "Hand Gestures"
  },
  {
    "emoji": "✊️🏼",
    "category": "Hand Gestures"
  },
  {
    "emoji": "✋️🏽",
    "category": "Hand Gestures"
  },
  {
    "emoji": "👨🏾‍🚀",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "👩🏽‍🎨",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "👩🏽‍🍳",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "👩🏼‍🌾",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "👨🏿‍🏫",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "👨🏾‍⚕️",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "👨🏽‍🔧",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "👨🏽‍🚒",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "👮🏻",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "🕵🏻",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "💂🏼",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "👷🏼",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "🤴🏼",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "👸🏽",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "👳🏻",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "👲🏼",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "🧕🏻",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "🎅🏿",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "🦸🏼",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "🦹🏼",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "🧙🏼",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "🧚🏻",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "🧛🏿",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "🧜🏻",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "🧞",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "🧟",
    "category": "People — Roles & Fantasy"
  },
  {
    "emoji": "💆🏿",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "💇🏽",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🚶🏻",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🏃🏿",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "💃🏽",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🕺🏻",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🕴🏿",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🧗🏿",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🏇🏿",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "⛷️",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🏂🏾",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🏌🏽",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🏄🏽",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🚣🏽",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🏊🏾",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "⛹️🏼",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🏋🏾",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🚴🏿",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🚵🏽",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🤸🏾",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🤼",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🤽🏼",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🤾🏼",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🤹🏽",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🧘🏾",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🛀🏼",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "🛌🏼",
    "category": "People — Actions & Poses"
  },
  {
    "emoji": "👀",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👁️",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👂🏾",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👃🏼",
    "category": "People — Body & Family"
  },
  {
    "emoji": "🧠",
    "category": "People — Body & Family"
  },
  {
    "emoji": "🦷",
    "category": "People — Body & Family"
  },
  {
    "emoji": "🦴",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👄",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👅",
    "category": "People — Body & Family"
  },
  {
    "emoji": "💪🏾",
    "category": "People — Body & Family"
  },
  {
    "emoji": "🦵🏾",
    "category": "People — Body & Family"
  },
  {
    "emoji": "🦶🏻",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👶🏼",
    "category": "People — Body & Family"
  },
  {
    "emoji": "🧒🏻",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👦🏽",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👧🏾",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👨🏽",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👩🏿",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👵🏼",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👴🏻",
    "category": "People — Body & Family"
  },
  {
    "emoji": "👵🏾",
    "category": "People — Body & Family"
  },
  {
    "emoji": "🐶",
    "category": "Animals"
  },
  {
    "emoji": "🐱",
    "category": "Animals"
  },
  {
    "emoji": "🐭",
    "category": "Animals"
  },
  {
    "emoji": "🐹",
    "category": "Animals"
  },
  {
    "emoji": "🐰",
    "category": "Animals"
  },
  {
    "emoji": "🦊",
    "category": "Animals"
  },
  {
    "emoji": "🐻",
    "category": "Animals"
  },
  {
    "emoji": "🐼",
    "category": "Animals"
  },
  {
    "emoji": "🐨",
    "category": "Animals"
  },
  {
    "emoji": "🐯",
    "category": "Animals"
  },
  {
    "emoji": "🦁",
    "category": "Animals"
  },
  {
    "emoji": "🐮",
    "category": "Animals"
  },
  {
    "emoji": "🐷",
    "category": "Animals"
  },
  {
    "emoji": "🐸",
    "category": "Animals"
  },
  {
    "emoji": "🐵",
    "category": "Animals"
  },
  {
    "emoji": "🙈",
    "category": "Animals"
  },
  {
    "emoji": "🐔",
    "category": "Animals"
  },
  {
    "emoji": "🐧",
    "category": "Animals"
  },
  {
    "emoji": "🐦",
    "category": "Animals"
  },
  {
    "emoji": "🐤",
    "category": "Animals"
  },
  {
    "emoji": "🦆",
    "category": "Animals"
  },
  {
    "emoji": "🦅",
    "category": "Animals"
  },
  {
    "emoji": "🦉",
    "category": "Animals"
  },
  {
    "emoji": "🦇",
    "category": "Animals"
  },
  {
    "emoji": "🐺",
    "category": "Animals"
  },
  {
    "emoji": "🐗",
    "category": "Animals"
  },
  {
    "emoji": "🐴",
    "category": "Animals"
  },
  {
    "emoji": "🦄",
    "category": "Animals"
  },
  {
    "emoji": "🐝",
    "category": "Animals"
  },
  {
    "emoji": "🐛",
    "category": "Animals"
  },
  {
    "emoji": "🦋",
    "category": "Animals"
  },
  {
    "emoji": "🐌",
    "category": "Animals"
  },
  {
    "emoji": "🐞",
    "category": "Animals"
  },
  {
    "emoji": "🐜",
    "category": "Animals"
  },
  {
    "emoji": "🕷️",
    "category": "Animals"
  },
  {
    "emoji": "🦂",
    "category": "Animals"
  },
  {
    "emoji": "🐢",
    "category": "Animals"
  },
  {
    "emoji": "🐍",
    "category": "Animals"
  },
  {
    "emoji": "🦎",
    "category": "Animals"
  },
  {
    "emoji": "🐙",
    "category": "Animals"
  },
  {
    "emoji": "🦑",
    "category": "Animals"
  },
  {
    "emoji": "🦀",
    "category": "Animals"
  },
  {
    "emoji": "🦞",
    "category": "Animals"
  },
  {
    "emoji": "🦐",
    "category": "Animals"
  },
  {
    "emoji": "🐠",
    "category": "Animals"
  },
  {
    "emoji": "🐟",
    "category": "Animals"
  },
  {
    "emoji": "🐡",
    "category": "Animals"
  },
  {
    "emoji": "🐬",
    "category": "Animals"
  },
  {
    "emoji": "🦈",
    "category": "Animals"
  },
  {
    "emoji": "🐳",
    "category": "Animals"
  },
  {
    "emoji": "🐊",
    "category": "Animals"
  },
  {
    "emoji": "🐆",
    "category": "Animals"
  },
  {
    "emoji": "🦓",
    "category": "Animals"
  },
  {
    "emoji": "🦍",
    "category": "Animals"
  },
  {
    "emoji": "🦧",
    "category": "Animals"
  },
  {
    "emoji": "🐘",
    "category": "Animals"
  },
  {
    "emoji": "🦏",
    "category": "Animals"
  },
  {
    "emoji": "🦛",
    "category": "Animals"
  },
  {
    "emoji": "🐪",
    "category": "Animals"
  },
  {
    "emoji": "🦒",
    "category": "Animals"
  },
  {
    "emoji": "🦘",
    "category": "Animals"
  },
  {
    "emoji": "🐑",
    "category": "Animals"
  },
  {
    "emoji": "🐐",
    "category": "Animals"
  },
  {
    "emoji": "🦙",
    "category": "Animals"
  },
  {
    "emoji": "🐓",
    "category": "Animals"
  },
  {
    "emoji": "🦃",
    "category": "Animals"
  },
  {
    "emoji": "🦚",
    "category": "Animals"
  },
  {
    "emoji": "🦜",
    "category": "Animals"
  },
  {
    "emoji": "🦢",
    "category": "Animals"
  },
  {
    "emoji": "🦩",
    "category": "Animals"
  },
  {
    "emoji": "🦔",
    "category": "Animals"
  },
  {
    "emoji": "🦦",
    "category": "Animals"
  },
  {
    "emoji": "🦥",
    "category": "Animals"
  },
  {
    "emoji": "🦨",
    "category": "Animals"
  },
  {
    "emoji": "🦡",
    "category": "Animals"
  },
  {
    "emoji": "🐉",
    "category": "Animals"
  },
  {
    "emoji": "🌵",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🎄",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🌲",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🌳",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🌴",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🌿",
    "category": "Plants & Nature"
  },
  {
    "emoji": "☘️",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🍀",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🍃",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🍂",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🍁",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🍄",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🐚",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🪨",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🌾",
    "category": "Plants & Nature"
  },
  {
    "emoji": "💐",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🌷",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🌹",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🥀",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🌺",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🌼",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🌻",
    "category": "Plants & Nature"
  },
  {
    "emoji": "🍎",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍏",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍐",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍊",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍋",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍌",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍉",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍇",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍓",
    "category": "Food & Drink"
  },
  {
    "emoji": "🫐",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍈",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍒",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍑",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥭",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍍",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥥",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥝",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍅",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍆",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥑",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥦",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥬",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥒",
    "category": "Food & Drink"
  },
  {
    "emoji": "🌶️",
    "category": "Food & Drink"
  },
  {
    "emoji": "🫑",
    "category": "Food & Drink"
  },
  {
    "emoji": "🌽",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥕",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥔",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍠",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥐",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥯",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍞",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥖",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥨",
    "category": "Food & Drink"
  },
  {
    "emoji": "🧀",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥚",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍳",
    "category": "Food & Drink"
  },
  {
    "emoji": "🧈",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥞",
    "category": "Food & Drink"
  },
  {
    "emoji": "🧇",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥓",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥩",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍗",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍖",
    "category": "Food & Drink"
  },
  {
    "emoji": "🌭",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍔",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍟",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍕",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥪",
    "category": "Food & Drink"
  },
  {
    "emoji": "🌮",
    "category": "Food & Drink"
  },
  {
    "emoji": "🌯",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥙",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥗",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍿",
    "category": "Food & Drink"
  },
  {
    "emoji": "🧂",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥫",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍝",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍜",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍤",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍚",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥠",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍦",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍨",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍩",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍪",
    "category": "Food & Drink"
  },
  {
    "emoji": "🎂",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍰",
    "category": "Food & Drink"
  },
  {
    "emoji": "🧁",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥧",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍫",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍬",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍭",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍯",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍼",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥛",
    "category": "Food & Drink"
  },
  {
    "emoji": "☕️",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍵",
    "category": "Food & Drink"
  },
  {
    "emoji": "🧃",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥤",
    "category": "Food & Drink"
  },
  {
    "emoji": "🧋",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍺",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥂",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍷",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍹",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍾",
    "category": "Food & Drink"
  },
  {
    "emoji": "🧊",
    "category": "Food & Drink"
  },
  {
    "emoji": "🥄",
    "category": "Food & Drink"
  },
  {
    "emoji": "🍴",
    "category": "Food & Drink"
  },
  {
    "emoji": "🚗",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚕",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚌",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🏎️",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚑",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚒",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚓",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚚",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚜",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🛵",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🏍️",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚲",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🛴",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚂",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "✈️",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚀",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🛸",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚁",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "⛵️",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚢",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "⚓️",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🚦",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "🛑",
    "category": "Transit & Vehicles"
  },
  {
    "emoji": "⚽️",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🏀",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🏈",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "⚾️",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎾",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🏐",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎱",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🏓",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🏸",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🥊",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "⛳️",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎣",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎿",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🛷",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎯",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎳",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎮",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎲",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🧩",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🃏",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎰",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🪁",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎪",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎨",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎭",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎬",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎤",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎧",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎹",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🥁",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎷",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎺",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎸",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🎻",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🪕",
    "category": "Sports, Games & Instruments"
  },
  {
    "emoji": "🏠",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🏡",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🏥",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🏢",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🏭",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🏰",
    "category": "Buildings & Places"
  },
  {
    "emoji": "⛪️",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🗽",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🎡",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🎢",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🎠",
    "category": "Buildings & Places"
  },
  {
    "emoji": "⛲️",
    "category": "Buildings & Places"
  },
  {
    "emoji": "⛺️",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🏔️",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🌋",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🏖️",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🏝️",
    "category": "Buildings & Places"
  },
  {
    "emoji": "🏟️",
    "category": "Buildings & Places"
  },
  {
    "emoji": "☀️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "🌤️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "🌥️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "☁️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "🌦️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "🌧️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "⛈️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "🌩️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "❄️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "☃️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "🌪️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "🌈",
    "category": "Weather & Sky"
  },
  {
    "emoji": "☔️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "⚡️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "🔥",
    "category": "Weather & Sky"
  },
  {
    "emoji": "💧",
    "category": "Weather & Sky"
  },
  {
    "emoji": "🌊",
    "category": "Weather & Sky"
  },
  {
    "emoji": "🌙",
    "category": "Weather & Sky"
  },
  {
    "emoji": "⭐️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "✨️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "☄️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "🌡️",
    "category": "Weather & Sky"
  },
  {
    "emoji": "❤️",
    "category": "Symbols & Money"
  },
  {
    "emoji": "💔",
    "category": "Symbols & Money"
  },
  {
    "emoji": "✝️",
    "category": "Symbols & Money"
  },
  {
    "emoji": "☮️",
    "category": "Symbols & Money"
  },
  {
    "emoji": "💰",
    "category": "Symbols & Money"
  },
  {
    "emoji": "💵",
    "category": "Symbols & Money"
  },
  {
    "emoji": "💳",
    "category": "Symbols & Money"
  },
  {
    "emoji": "🪙",
    "category": "Symbols & Money"
  },
  {
    "emoji": "💸",
    "category": "Symbols & Money"
  },
  {
    "emoji": "🧾",
    "category": "Symbols & Money"
  },
  {
    "emoji": "🕐",
    "category": "Symbols & Money"
  },
  {
    "emoji": "🎵",
    "category": "Symbols & Money"
  },
  {
    "emoji": "🔮",
    "category": "Symbols & Money"
  },
  {
    "emoji": "🪄",
    "category": "Symbols & Money"
  },
  {
    "emoji": "🗝️",
    "category": "Symbols & Money"
  },
  {
    "emoji": "🔑",
    "category": "Symbols & Money"
  },
  {
    "emoji": "📚",
    "category": "Office & Stationery"
  },
  {
    "emoji": "📖",
    "category": "Office & Stationery"
  },
  {
    "emoji": "✏️",
    "category": "Office & Stationery"
  },
  {
    "emoji": "🖊️",
    "category": "Office & Stationery"
  },
  {
    "emoji": "🖍️",
    "category": "Office & Stationery"
  },
  {
    "emoji": "📝",
    "category": "Office & Stationery"
  },
  {
    "emoji": "📌",
    "category": "Office & Stationery"
  },
  {
    "emoji": "📎",
    "category": "Office & Stationery"
  },
  {
    "emoji": "✂️",
    "category": "Office & Stationery"
  },
  {
    "emoji": "📏",
    "category": "Office & Stationery"
  },
  {
    "emoji": "📐",
    "category": "Office & Stationery"
  },
  {
    "emoji": "📁",
    "category": "Office & Stationery"
  },
  {
    "emoji": "📅",
    "category": "Office & Stationery"
  },
  {
    "emoji": "🗑️",
    "category": "Office & Stationery"
  },
  {
    "emoji": "🔒",
    "category": "Office & Stationery"
  },
  {
    "emoji": "🔓",
    "category": "Office & Stationery"
  },
  {
    "emoji": "💉",
    "category": "Medical & Science"
  },
  {
    "emoji": "💊",
    "category": "Medical & Science"
  },
  {
    "emoji": "🩺",
    "category": "Medical & Science"
  },
  {
    "emoji": "🧪",
    "category": "Medical & Science"
  },
  {
    "emoji": "🧬",
    "category": "Medical & Science"
  },
  {
    "emoji": "🔬",
    "category": "Medical & Science"
  },
  {
    "emoji": "🔭",
    "category": "Medical & Science"
  },
  {
    "emoji": "🧲",
    "category": "Medical & Science"
  },
  {
    "emoji": "👑",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👒",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🎩",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🧢",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "⛑️",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👓",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🕶️",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👔",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👕",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👖",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🧥",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🥼",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🦺",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👗",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👙",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👚",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👛",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👜",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👝",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🎒",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👞",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👟",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🥾",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👠",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👡",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "👢",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🧦",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🧤",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🧣",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🧳",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "☂️",
    "category": "Clothing & Accessories"
  },
  {
    "emoji": "🔨",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🪓",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🔧",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "⚙️",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🪚",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🧰",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "⛓️",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🧱",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🪜",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🧹",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🧺",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🧻",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🪣",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🧼",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🪥",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🛁",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🚿",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🪒",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🧴",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🔋",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🔌",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "💡",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🔦",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🕯️",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "📱",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "☎️",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "💻",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🖨️",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "⌨️",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "📷",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🎥",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "📺",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "⏱️",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🧭",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🎁",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🎀",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🎈",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🎉",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🎊",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🧨",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🪅",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🕹️",
    "category": "Household, Tools & Misc Objects"
  },
  {
    "emoji": "🇺🇸",
    "category": "Flags"
  },
  {
    "emoji": "🏴‍☠️",
    "category": "Flags"
  }
]
