export const WORDS_A = [
  "MAPLE","RIVER","OCEAN","SUNRISE","VELVET","COPPER","SILVER","EMBER","FOREST","CLOUD",
  "IVORY","SAPPHIRE","SPRING","SUMMER","WINTER","AUTUMN","MORNING","MIDNIGHT","ORCHID","LANTERN",
  "PINE","CEDAR","MEADOW","CANYON","HARBOR","ISLAND","VALLEY","MOUNTAIN","GARDEN","BREEZE",
  "COMET","ROCKET","MIRROR","CARPET","POCKET","BRIDGE","CANDLE","PILOT","CIRCUS","PARADE",
  "BLOSSOM","CORAL","PEBBLE","MARBLE","FROST","FLAME","SPARK","SHADOW","WONDER","GLIMMER",
  "HONEY","BUTTER","COOKIE","WAFFLE","MUFFIN","BAGEL","COCOA","LATTE","LEMON","MANGO",
  "PLUM","PEACH","BERRY","OLIVE","BASIL","PEPPER","GINGER","SUGAR","SALMON","TURKEY",
  "PANDA","TIGER","OTTER","EAGLE","FALCON","ROBIN","WHALE","DOLPHIN","KOALA","ZEBRA",
  "LLAMA","HORSE","MONKEY","RABBIT","BADGER","BEAVER","COYOTE","WOLF","FOX","MOOSE",
  "BISON","GIRAFFE","JAGUAR","COBRA","VIPER","GECKO","TURTLE","SEAL","SHARK","RAY",
]

export const WORDS_B = [
  "NINJA","SAMURAI","KNIGHT","WIZARD","RANGER","SCOUT","CAPTAIN","DOCTOR","ARTIST","BAKER",
  "ENGINE","HAMMER","ANCHOR","COMPASS","RADAR","SATELLITE","CAMERA","GUITAR","PIANO","DRUM",
  "PLANET","GALAXY","NEBULA","ASTEROID","ECLIPSE","AURORA","HORIZON","SKYLINE","CASTLE","TORCH",
  "LANTERN","TOWER","TEMPLE","PALACE","CAVERN","LAGOON","GLACIER","TUNDRA","DESERT","JUNGLE",
  "RAPIDS","SUMMIT","CRATER","CANYON","DELTA","FJORD","STEPPE","SAVANNA","MARSH","REEF",
  "IRON","BRONZE","QUARTZ","AMBER","JADE","PEARL","RUBY","ONYX","LAPIS","TOPAZ",
  "STORM","BLIZZARD","TYPHOON","THUNDER","LIGHTNING","CYCLONE","MONSOON","SQUALL","DRIZZLE","FOG",
  "COMET","METEOR","PULSAR","QUASAR","NEBULA","COSMOS","ZENITH","SOLSTICE","EQUINOX","VOID",
]

export function randomCode() {
  const a = WORDS_A[Math.floor(Math.random() * WORDS_A.length)]
  const b = WORDS_B[Math.floor(Math.random() * WORDS_B.length)]
  return `${a}${b}`
}

export function splitCode(code) {
  for (const w of WORDS_A) {
    if (code.startsWith(w)) return [w, code.slice(w.length)]
  }
  return [code, ""]
}
